// Country name → ISO 3166-1 alpha-3 mapping
// Covers the COUNTRIES list from countries.ts
export const COUNTRY_TO_ISO3: Record<string, string> = {
  "Afghanistan": "AFG", "Albania": "ALB", "Algeria": "DZA", "Andorra": "AND",
  "Angola": "AGO", "Antigua and Barbuda": "ATG", "Argentina": "ARG", "Armenia": "ARM",
  "Australia": "AUS", "Austria": "AUT", "Azerbaijan": "AZE", "Bahamas": "BHS",
  "Bahrain": "BHR", "Bangladesh": "BGD", "Barbados": "BRB", "Belarus": "BLR",
  "Belgium": "BEL", "Belize": "BLZ", "Benin": "BEN", "Bhutan": "BTN",
  "Bolivia": "BOL", "Bosnia and Herzegovina": "BIH", "Botswana": "BWA", "Brazil": "BRA",
  "Brunei": "BRN", "Bulgaria": "BGR", "Burkina Faso": "BFA", "Burundi": "BDI",
  "Cabo Verde": "CPV", "Cambodia": "KHM", "Cameroon": "CMR", "Canada": "CAN",
  "Central African Republic": "CAF", "Chad": "TCD", "Chile": "CHL", "China": "CHN",
  "Colombia": "COL", "Comoros": "COM", "Congo": "COG", "Costa Rica": "CRI",
  "Croatia": "HRV", "Cuba": "CUB", "Cyprus": "CYP", "Czech Republic": "CZE",
  "Democratic Republic of the Congo": "COD", "Denmark": "DNK", "Djibouti": "DJI",
  "Dominica": "DMA", "Dominican Republic": "DOM", "East Timor": "TLS", "Ecuador": "ECU",
  "Egypt": "EGY", "El Salvador": "SLV", "Equatorial Guinea": "GNQ", "Eritrea": "ERI",
  "Estonia": "EST", "Eswatini": "SWZ", "Ethiopia": "ETH", "Fiji": "FJI",
  "Finland": "FIN", "France": "FRA", "Gabon": "GAB", "Gambia": "GMB",
  "Georgia": "GEO", "Germany": "DEU", "Ghana": "GHA", "Greece": "GRC",
  "Grenada": "GRD", "Guatemala": "GTM", "Guinea": "GIN", "Guinea-Bissau": "GNB",
  "Guyana": "GUY", "Haiti": "HTI", "Honduras": "HND", "Hungary": "HUN",
  "Iceland": "ISL", "India": "IND", "Indonesia": "IDN", "Iran": "IRN",
  "Iraq": "IRQ", "Ireland": "IRL", "Israel": "ISR", "Italy": "ITA",
  "Ivory Coast": "CIV", "Jamaica": "JAM", "Japan": "JPN", "Jordan": "JOR",
  "Kazakhstan": "KAZ", "Kenya": "KEN", "Kiribati": "KIR", "Kosovo": "XKX",
  "Kuwait": "KWT", "Kyrgyzstan": "KGZ", "Laos": "LAO", "Latvia": "LVA",
  "Lebanon": "LBN", "Lesotho": "LSO", "Liberia": "LBR", "Libya": "LBY",
  "Liechtenstein": "LIE", "Lithuania": "LTU", "Luxembourg": "LUX",
  "Madagascar": "MDG", "Malawi": "MWI", "Malaysia": "MYS", "Maldives": "MDV",
  "Mali": "MLI", "Malta": "MLT", "Marshall Islands": "MHL", "Mauritania": "MRT",
  "Mauritius": "MUS", "Mexico": "MEX", "Micronesia": "FSM", "Moldova": "MDA",
  "Monaco": "MCO", "Mongolia": "MNG", "Montenegro": "MNE", "Morocco": "MAR",
  "Mozambique": "MOZ", "Myanmar": "MMR", "Namibia": "NAM", "Nauru": "NRU",
  "Nepal": "NPL", "Netherlands": "NLD", "New Zealand": "NZL", "Nicaragua": "NIC",
  "Niger": "NER", "Nigeria": "NGA", "North Korea": "PRK", "North Macedonia": "MKD",
  "Norway": "NOR", "Oman": "OMN", "Pakistan": "PAK", "Palau": "PLW",
  "Palestine": "PSE", "Panama": "PAN", "Papua New Guinea": "PNG", "Paraguay": "PRY",
  "Peru": "PER", "Philippines": "PHL", "Poland": "POL", "Portugal": "PRT",
  "Qatar": "QAT", "Romania": "ROU", "Russia": "RUS", "Rwanda": "RWA",
  "Saint Kitts and Nevis": "KNA", "Saint Lucia": "LCA",
  "Saint Vincent and the Grenadines": "VCT", "Samoa": "WSM", "San Marino": "SMR",
  "Sao Tome and Principe": "STP", "Saudi Arabia": "SAU", "Senegal": "SEN",
  "Serbia": "SRB", "Seychelles": "SYC", "Sierra Leone": "SLE", "Singapore": "SGP",
  "Slovakia": "SVK", "Slovenia": "SVN", "Solomon Islands": "SLB", "Somalia": "SOM",
  "South Africa": "ZAF", "South Korea": "KOR", "South Sudan": "SSD", "Spain": "ESP",
  "Sri Lanka": "LKA", "Sudan": "SDN", "Suriname": "SUR", "Sweden": "SWE",
  "Switzerland": "CHE", "Syria": "SYR", "Taiwan": "TWN", "Tajikistan": "TJK",
  "Tanzania": "TZA", "Thailand": "THA", "Togo": "TGO", "Tonga": "TON",
  "Trinidad and Tobago": "TTO", "Tunisia": "TUN", "Turkey": "TUR",
  "Turkmenistan": "TKM", "Tuvalu": "TUV", "Uganda": "UGA", "Ukraine": "UKR",
  "United Arab Emirates": "ARE", "United Kingdom": "GBR", "United States": "USA",
  "Uruguay": "URY", "Uzbekistan": "UZB", "Vanuatu": "VUT", "Vatican City": "VAT",
  "Venezuela": "VEN", "Vietnam": "VNM", "Yemen": "YEM", "Zambia": "ZMB",
  "Zimbabwe": "ZWE",
};

// ISO 3166-1 alpha-2 → country name (for airport iso_country lookups)
export const ISO2_TO_COUNTRY: Record<string, string> = {
  US: "United States", CA: "Canada", MX: "Mexico", GB: "United Kingdom",
  IE: "Ireland", FR: "France", DE: "Germany", IT: "Italy", ES: "Spain",
  NL: "Netherlands", BE: "Belgium", CH: "Switzerland", AT: "Austria",
  JP: "Japan", KR: "South Korea", CN: "China", TW: "Taiwan", SG: "Singapore",
  TH: "Thailand", MY: "Malaysia", ID: "Indonesia", PH: "Philippines",
  IN: "India", AU: "Australia", NZ: "New Zealand", BR: "Brazil",
  AR: "Argentina", CL: "Chile", CO: "Colombia", PE: "Peru", UY: "Uruguay",
  IS: "Iceland", NO: "Norway", SE: "Sweden", DK: "Denmark", FI: "Finland",
  PT: "Portugal", GR: "Greece", TR: "Turkey", IL: "Israel", AE: "United Arab Emirates",
  SA: "Saudi Arabia", EG: "Egypt", ZA: "South Africa", KE: "Kenya",
  CR: "Costa Rica", PA: "Panama", CU: "Cuba", JM: "Jamaica",
  DO: "Dominican Republic", BS: "Bahamas", TT: "Trinidad and Tobago",
  HK: "Hong Kong", VN: "Vietnam", KH: "Cambodia", LA: "Laos", MM: "Myanmar",
  BD: "Bangladesh", LK: "Sri Lanka", NP: "Nepal", PK: "Pakistan",
  QA: "Qatar", BH: "Bahrain", KW: "Kuwait", OM: "Oman",
  RU: "Russia", UA: "Ukraine", PL: "Poland", CZ: "Czech Republic",
  HU: "Hungary", RO: "Romania", BG: "Bulgaria", HR: "Croatia",
  LT: "Lithuania", LV: "Latvia", EE: "Estonia", LU: "Luxembourg",
  MT: "Malta", CY: "Cyprus", FJ: "Fiji", WS: "Samoa",
};

// US state name → abbreviation mapping
export const STATE_TO_ABBR: Record<string, string> = {
  "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
  "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
  "Florida": "FL", "Georgia": "GA", "Hawaii": "HI", "Idaho": "ID",
  "Illinois": "IL", "Indiana": "IN", "Iowa": "IA", "Kansas": "KS",
  "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME", "Maryland": "MD",
  "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN", "Mississippi": "MS",
  "Missouri": "MO", "Montana": "MT", "Nebraska": "NE", "Nevada": "NV",
  "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY",
  "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH", "Oklahoma": "OK",
  "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI", "South Carolina": "SC",
  "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX", "Utah": "UT",
  "Vermont": "VT", "Virginia": "VA", "Washington": "WA", "West Virginia": "WV",
  "Wisconsin": "WI", "Wyoming": "WY", "District of Columbia": "DC",
};
